version: 0.0
os: linux
files:
  - source: /web.html
    destination: /usr/share/nginx/html/index.html 
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root
